export class InvalidURLError extends Error {}
export class CannotFindDIDKeyPairIndex extends Error {}
export class CannotFindDIDPrivateKey extends Error {}
export class InvitationHasNoFromDIDError extends Error {}
export class NoValidServiceEndpointError extends Error {}
export class InvitationIsInvalidError extends Error {}
export class NoConnectionOpenError extends Error {}
export class NoHandshakeResponseError extends Error {}
export class UnknownInvitationTypeError extends Error {}
export class UnknownPrismOnboardingTypeError extends Error {}
export class FailedToOnboardError extends Error {}
export class InvalidPickupDeliveryMessageError extends Error {}
export class InvalidOfferCredentialMessageError extends Error {}
export class InvalidProposedCredentialMessageError extends Error {}
export class InvalidIssueCredentialMessageError extends Error {}
export class InvalidRequestCredentialMessageError extends Error {}
export class InvalidPresentationMessageError extends Error {}
export class InvalidRequestPresentationMessageError extends Error {}
export class InvalidProposePresentationMessageError extends Error {}
export class InvalidMediationGrantMessageError extends Error {}
export class InvalidMessageError extends Error {}
export class NoMediatorAvailableError extends Error {}
export class MediationRequestFailedError extends Error {}
export class InvalidStepError extends Error {}
