import type { Metadata } from 'next'
import { addRxPlugin } from "rxdb";
import { RxDBDevModePlugin } from "rxdb/plugins/dev-mode";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

addRxPlugin(RxDBDevModePlugin);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  )
}
