export * from "./Api";
export * from "./DID";
export * from "./DIDDocument";
export * from "./DIDPair";
export * from "./DIDResolver";
export * from "./DIDUrl";
export * from "./Errors";
export * from "./JWTVerifiableCredential";
export * from "./KeyPair";
export * from "./Mediator";
export * from "./Message";
export * from "./MessageAttachment";
export * from "./PeerDID";
export * from "./PrismDIDInfo";
export * from "./PrismDIDMethodId";
export * from "./keyManagement";
export * from "./Seed";
export * from "./SeedWords";
export * from "./Signature";
export * from "./WordList";
export * from "./VerifiableCredential";

export type JsonString = string;
